// wordPairs.js
// Edit this file to add or change word pairs for the Undercover Game.

const wordPairs = [
  ['cat', 'dog'],
  ['pen', 'pencil'],
  ['river', 'lake'],
  ['mountain', 'hill'],
  ['biryani', 'pulao'],
  ['rasgulla', 'gulabjamun'],
  ['namaste', 'salaam'],
  ['rajma', 'chole'],
  ['dosa', 'idli'],
  ['samosa', 'kachori'],
  ['rickshaw', 'auto'],
  ['umpire', 'referee'],
  ['medal', 'trophy'],
  ['dhol', 'tabla'],
  ['lungi', 'dhoti'],
  ['book', 'novel'],
  ['ship', 'boat'],
  ['candle', 'torch'],
  ['rocket', 'missile'],
  ['gasoline', 'petrol'],
  ['scarf', 'shawl'],
  ['microwave', 'oven'],
  ['backpack', 'handbag'],
  ['elevator', 'escalator'],
  ['apple', 'samsung'],
  ['Tata', 'Mahindra'],
  ['chai', 'coffee'],
  ['achar', 'chutney'],
  ['bhel', 'chaat'],
  ['sev', 'bhujia'],
  ['Oktoberfest', 'Weihnachtsmarkt'],
  ['coca cola', 'pepsi'],
  ['lays', 'kurkure'],
  ['facebook', 'instagram'],
  ['Lock', 'Key'],
  ['Japan', 'China'],
  ['Computer', 'Laptop'],
  ['Motorbike', 'Bicycle'],
  ['Cloud', 'Sky'],
  ['Desk', 'Drawer'],
  ['Sunset', 'Sunrise'],
  ['Earth', 'Planet'],
  ['Spoon', 'Fork'],
  ['bottle', 'glass'],
  ['plate', 'bowl'],
  ['knife', 'fork']
];

export default wordPairs;
